### ISSUE TITLE
How to connect several drones

### ISSUE THREAD

**Issue by shiva02** [voodootikigod/node-rolling-spider#40] opened 2015-06-04 00:25 UTC
Hi everyone, i try to take off 2 rolling spider at the same time by creating two instances and by specifying their uuid but the program sequence is random, sometimes drone 1 and sometimes drone 2, the other times both. Can you help me, can i have a simple example?
Thanks, best regards

Seb V

**Comment by voodootikigod** [comment] 2015-06-04 00:31
It should never do both.. That's an odd case swarm (more than 1) isn't yet
supported. Variable single is supported

On Wednesday, June 3, 2015, shiva02 notifications@github.com wrote:

> Hi everyone, i try to take off 2 rolling spider at the same time by
> creating two instances and by specifying their uuid but the program
> sequence is random, sometimes drone 1 and sometimes drone 2, the other
> times both. Can you help me, can i have a simple example?
> Thanks, best regards
> 
> Seb V
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FluffyJack/node-rolling-spider/issues/40.

## 

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_Maker of Improbable Things:_ JSConf http://jsconf.com/ | RobotsConf
http://robotsconf.com/ | Beer.js http://beerjs.com | Logo.js
https://github.com/voodootikigod/logo.js | node-serialport
http://nodebots.io/

**Comment by shiva02** [comment] 2015-06-04 00:37
Ah pity, is planned one day perhaps? I'll keep you posted on tests I plan to do.

**Comment by voodootikigod** [comment] 2015-06-04 00:52
Yup. And soon as well.

On Wednesday, June 3, 2015, shiva02 notifications@github.com wrote:

> Ah pity, is planned one day perhaps? I'll keep you posted on tests I plan
> to do.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FluffyJack/node-rolling-spider/issues/40#issuecomment-108658159
> .

## 

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.

**Comment by voodootikigod** [comment] 2015-06-08 12:03
https://github.com/FluffyJack/node-rolling-spider/tree/swarm

Readme coming soon but short is in 

https://github.com/FluffyJack/node-rolling-spider/blob/swarm/eg/swarm.js

**Comment by voodootikigod** [comment] 2015-06-08 12:10
Duplicate of #31

**Closed as completed by voodootikigod** 2015-06-08 12:10 UTC

**Comment by shiva02** [comment] 2015-06-08 12:45
Thank you very much, I had not seen this post.
By
